/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.prashanth.spring.websockets.SpringWebsocketsApplication;
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        SpringWebsocketsApplication classUnderTest = new SpringWebsocketsApplication();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
